# Generated by Django 4.2.4 on 2023-08-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0002_clientes_devoluciones_delete_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='numero_cliente',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefono_cliente',
        ),
    ]
