# Generated by Django 4.2.4 on 2023-08-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0004_remove_producto_fecha_de_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='entregado',
        ),
    ]
