# Generated by Django 4.2.4 on 2023-08-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0005_remove_envio_entregado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devoluciones',
            new_name='Devolucion',
        ),
    ]
