# Generated by Django 4.2.4 on 2023-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCoder', '0006_rename_devoluciones_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='fecha_de_entrega',
            field=models.IntegerField(),
        ),
    ]
